# Generated by Django 4.2.29 on 2026-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rios',
            name='risco_inundacao',
            field=models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto'), (4, 'Muito Alto')]),
        ),
    ]
