# Generated by Django 4.2.29 on 2026-05-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('rios', '0002_alter_rios_risco_inundacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='rios',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rios', to='usuarios.usuario'),
        ),
    ]
