# Generated by Django 4.2.29 on 2026-05-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_is_defesa_civil'),
        ('rios', '0003_rios_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('descricao', models.TextField()),
                ('nivel_risco', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pontos_risco_criados', to='usuarios.usuario')),
                ('rio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_risco', to='rios.rios')),
            ],
        ),
    ]
