# Generated by Django 4.2.29 on 2026-05-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0004_pontorisco'),
    ]

    operations = [
        migrations.AddField(
            model_name='rios',
            name='descricao_gemini',
            field=models.TextField(blank=True, null=True),
        ),
    ]
