# Generated by Django 4.2.29 on 2026-05-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0005_rios_descricao_gemini'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontorisco',
            name='nivel_base',
            field=models.FloatField(default=1.0),
        ),
    ]
