# Generated by Django 4.2.29 on 2026-05-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0006_pontorisco_nivel_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontorisco',
            name='limite_alerta',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='pontorisco',
            name='limite_atencao',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='pontorisco',
            name='limite_emergencia',
            field=models.FloatField(default=3.5),
        ),
    ]
