# Generated by Django 4.2.29 on 2026-06-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0007_pontorisco_limite_alerta_pontorisco_limite_atencao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontorisco',
            name='nivel_risco',
        ),
        migrations.RemoveField(
            model_name='rios',
            name='risco_inundacao',
        ),
    ]
