# Generated by Django 4.2.29 on 2026-05-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_favoritos_usuario_token_alter_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API Token'),
        ),
    ]
