# Generated by Django 4.2.29 on 2026-05-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_defesa_civil',
            field=models.BooleanField(default=False, verbose_name='É Defesa Civil'),
        ),
    ]
