# Generated by Django 4.2.29 on 2026-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0005_rios_descricao_gemini'),
        ('usuarios', '0004_usuario_is_defesa_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='rios.pontorisco'),
        ),
    ]
