# Generated by Django 4.2.29 on 2026-06-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0008_remove_pontorisco_nivel_risco_and_more'),
        ('usuarios', '0005_usuario_telefone_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alertas',
            field=models.ManyToManyField(blank=True, related_name='alerted_by', to='rios.pontorisco'),
        ),
    ]
